### ISSUE TITLE
Can't set camera above 640p. (Help- This camera can peform higher then 720p..)

### ISSUE THREAD

**Issue by TheRealFame** [Z-Ray-Entertainment/Facetracker#14]
![image](https://github.com/user-attachments/assets/6be240be-509b-4827-b2d9-81a2324ad96a)

(From Flathub!)

**Comment by VortexAcherontic** [comment]
Hello there. Thank you for your report.

The reason Facetracker potentially shows lower resolutions and frame rates than what is actually supported by the webcam is due to OpenSeeFace itself.

Facetracker can only tell OpeSeeFace which camera to use, which resolution and at how much frames per second. Unfortunately I can not tell OSF the video codec it should actually use for capturing the frames from the webcam.
The later is exactly the issue why Facetracker might show lower resolutions and frame rates as officially supported by the device itself.

While a webcam might in theory support higher resolutions at a certain video codec (usually this is MJPEG) it can happen that the webcam reports the RAW video format and it's supported video formats using this codec first. While OSF does not allow for specifying the video codec it will always uses the very first reported video codec.

For example my webcam supports 1920x1080 @ 30 fps using MJPEG
but only 1920x1080 @ 5 fps using RAW.
Unfortunately it reports RAW first.

You can counter test this like this, inside the Facetracker flatpak there is a pre-compiled OpenSeeFace binary which in theory should run outside of flatpak on the host. You can find it at: `$HOME/.local/share/flatpak/app/de.z_ray.Facetracker/current/active/files/share/facetracker/osf/` there should be a file called `facetracker` run it as follows from a terminal sessions if your are inside that folder mentioned above:

`./facetracker -W 1280 -H 720 -c 0 -F 30`

-W is the width of the video
-H height of the video
-c is the camera to use. The first one usually has index 0 (You can also see this inside Facetracker)
-F is the frame rate

Here is an example of my 1080p@30fps camera (which only supports this frame rate using MJPEG but here is the result using OSF):

[Bildschirmaufnahme_20240914_102925.webm](https://github.com/user-attachments/assets/7dc41f73-4b84-4fd6-9b3c-6ef999a0a5d7)

If you can in fact use higher resolutions and frame rates and the video is still fluent in a VTubbing application let me now.

**Comment by TheRealFame** [comment]
![image](https://github.com/user-attachments/assets/8dc6343f-1e8b-47a6-ae9b-c194c0f80473)
Having issues opening it!

**Comment by VortexAcherontic** [comment]
Hm, yes I see. I think I need to add some debug info menu button to Facetracker to get all video formats found by Facetracker before it filtered them for use with OpenSeeFace.

**Comment by TheRealFame** [comment]
> Hm, yes I see. I think I need to add some debug info menu button to Facetracker to get all video formats found by Facetracker before it filtered them for use with OpenSeeFace.

Let me know when your able to patch it up 👀

**Comment by VortexAcherontic** [comment]
Hey ho @TheRealFame finally got some time to update Facetracker.
I just issued a new version which is on it's way to flathub within the next few hours it should be live.
This will be version 24.10.

What's probably of interest for you is the new debug information inside the about dialog which should show all available codecs and video formats supported by all of your video devices.

![image](https://github.com/user-attachments/assets/30bdc228-f7ca-4ff6-a10a-f94b46ea5544)
![image](https://github.com/user-attachments/assets/623f891b-f01a-4051-9edb-ccfc76224c53)
![image](https://github.com/user-attachments/assets/bba2ab25-1a3f-41f9-aa1a-d79c9ee37629)
![image](https://github.com/user-attachments/assets/bd87dc2b-ea84-4b6c-b20f-637ee4c413c2)

Please paste the debug info here so I can take a look at the actual issue here.

Kind regards,
V.

**Comment by TheRealFame** [comment]
[https://flathub.org/apps/de.z_ray.Facetracker](https://flathub.org/apps/de.z_ray.Facetracker)

It seems the build is still being sent to flathub! So I'll get to you when it sends the build to my debian based daily driver~

**Comment by TheRealFame** [comment]
`0 Razer Kiyo /sys/devices/pci0000:00/0000:00:08.1/0000:09:00.4/usb5/5-2/5-2:1.0/
default:
640x360@24
MJPG:
640x480@30
1920x1080@30
1280x720@60
1280x720@30
640x360@30
YUYV:
640x480@30
640x360@30
H264:
640x480@30
640x480@24
640x480@20
1920x1080@30
1920x1080@24
1920x1080@20
1280x720@30
1280x720@24
1280x720@20
640x360@30
640x360@24
640x360@20`

Yep, Seem's depending on the codec i can support these resolutions!

**Comment by VortexAcherontic** [comment]
Alright, thank you. I looked up the source code of open see face and can confirm [it does not care about the actual available video capabilities on Linux](https://github.com/emilianavt/OpenSeeFace/blob/e6e24efd2038ab778ac094bab21c2c18a7efbeb2/facetracker.py#L89-L123) (`os.name="nt"` is Windows) and will specifically [choose the rgb_raw](https://github.com/emilianavt/OpenSeeFace/blob/e6e24efd2038ab778ac094bab21c2c18a7efbeb2/facetracker.py#L159-L166) mode which is the `YUYV` codec.

Facetracker should offer you the following formats because of this:

```
default:
640x360@24

YUYV:
640x480@30
640x360@30
```

This is a limitation of osf I unfortunately can not fix on my end. 😢

**Comment by TheRealFame** [comment]
Oh, I understand! Is it impossible to spoof the application as running under windows with just some variable changes?

**Comment by TheRealFame** [comment]
Oh, I understand! Is it impossible to spoof the application as running under windows with just some variable changes?

**Comment by VortexAcherontic** [comment]
Even if, this would cause OpenSeeFace to try and use DirectShow which is an exclusive Window interface to receive Webcam capabilities on Windows which apparently is not available on Linux.

The easiest and long-term solution would be to improve OpenSeeFace to add proper support for Video4Linux which is the standard Webcam interface on Linux and the one Facetracker uses to identify Webcams and all their capabilities. I mean looking at the debug info Facetracker does now collect it is pretty much possible to access all these information on Linux. 😅

But since OpenSeeFace itself is build atop other libraries to access and read image data from Webcams it just might be that a different library further down the line is the reason why OSF does what it does.

At this point this is all speculation as I never looked into the matter that much.
